header mob
NataliiaChapai/team-project pull request #7
Opened 2021-11-14 18:05 UTC by AleksandrDiakov

Header для мобильного меню

2021-11-14 23:23 UTC, NataliiaChapai commented on src/sass/layout/_header.scss
> +    background-color: $mainColor;
Додати z-index: 15; є секції, які перебивають хедер.

2021-11-14 23:30 UTC, AleksandrDiakov commented on src/sass/layout/_header.scss
> +    background-color: $mainColor;
принято

2021-11-14 23:46 UTC, NataliiaChapai commented on src/partials/header.html
> +        <div class="header__burger">
<div> замінити на button

2021-11-14 23:47 UTC, NataliiaChapai commented on src/sass/layout/_header.scss
> +    height: 12px;
Додати cursor: pointer;

2021-11-14 23:49 UTC, NataliiaChapai requested changes
Потрібно внести зміни

2021-11-15 10:19 UTC, AleksandrDiakov commented on src/sass/layout/_header.scss
> +    height: 12px;
сделано

2021-11-15 10:22 UTC, AleksandrDiakov commented on src/partials/header.html
> +        <div class="header__burger">
при изменении тега на button, появляется кнопка которую нужно оформить. Думаю тогда нужен svg burger поставить. Но ранее я пробовал свой вариант бургер из палочек, через js все работало.

2021-11-15 12:00 UTC, NataliiaChapai approved these changes

2021-11-15 12:00 UTC, merged